#!/usr/bin/env python3
"""
Generate Supabase/Postgres migration artifacts from an Airtable metadata schema.

Outputs:
  sql/01_schema.sql                 -- CREATE TABLE for every Airtable table (stored fields only)
  docs/02-field-mapping-review.md   -- per-table human-readable mapping review
  docs/03-calculated-fields-todo.md -- every computed field + proposed recreation
  docs/calculated-fields.csv        -- same, as a trackable spreadsheet
  docs/04-er-diagram.md             -- Mermaid ER diagram of tables + relationships

Re-run any time the Airtable schema export changes.
"""
import json, csv, re, os

ROOT = r"C:\Claude Code"
SRC = os.path.join(ROOT, "airtable_schema_2026-06-25.json")

with open(SRC, encoding="utf-8-sig") as f:
    data = json.load(f)
tables = data["tables"]

# ---- lookups --------------------------------------------------------------
id2table = {t["id"]: t["name"] for t in tables}
field2name = {}      # fieldId -> field name
field2table = {}     # fieldId -> table name
for t in tables:
    for fld in t["fields"]:
        field2name[fld["id"]] = fld["name"]
        field2table[fld["id"]] = t["name"]

COMPUTED = {"formula", "rollup", "count", "lookup", "multipleLookupValues",
            "autoNumber", "createdTime", "lastModifiedTime", "createdBy",
            "lastModifiedBy", "button"}

# Postgres reserved words we must quote if they appear as identifiers
RESERVED = {"all","analyse","analyze","and","any","array","as","asc","both","case",
    "cast","check","collate","column","constraint","create","current_date","default",
    "desc","distinct","do","else","end","except","false","for","foreign","from","grant",
    "group","having","in","initially","intersect","into","limit","not","null","offset",
    "on","only","or","order","primary","references","returning","select","some","table",
    "then","to","true","union","unique","user","using","when","where","window","with","new","old"}

NUMERIC_TYPES = {"number", "currency", "percent", "duration", "rating", "count"}


def snake(name):
    s = re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").lower()
    s = re.sub(r"_+", "_", s)
    if not s:
        s = "col"
    if s[0].isdigit():
        s = "n_" + s
    return s


def ident(name):
    """Quote identifier only if needed."""
    return f'"{name}"' if name in RESERVED else name


def pg_type(fld):
    """Map a *stored* (non-computed) Airtable field to a Postgres type."""
    t = fld["type"]
    opts = fld.get("options") or {}
    if t in ("singleLineText", "multilineText", "url", "email", "phoneNumber",
             "richText", "barcode", "singleSelect"):
        return "text"
    if t == "multipleSelects":
        return "text[]"
    if t in NUMERIC_TYPES:
        return "numeric"
    if t == "checkbox":
        return "boolean"
    if t == "date":
        return "timestamptz" if opts.get("timeFormat") else "date"
    if t == "dateTime":
        return "timestamptz"
    if t in ("multipleRecordLinks", "singleRecordLink"):
        return "text[]"        # array of linked Airtable record IDs
    if t == "multipleAttachments":
        return "jsonb"
    if t in ("multipleCollaborators", "singleCollaborator"):
        return "jsonb"
    return "text"              # safe fallback


def describe_formula(opts):
    f = opts.get("formula", "")
    def repl(m):
        fid = m.group(1)
        return "{" + field2name.get(fid, fid) + "}"
    return re.sub(r"\{(fld[0-9A-Za-z]+)\}", repl, f)


def describe_rollup_lookup(fld):
    opts = fld.get("options") or {}
    link_fid = opts.get("recordLinkFieldId")
    src_fid = opts.get("fieldIdInLinkedTable")
    link_name = field2name.get(link_fid, link_fid)
    src_name = field2name.get(src_fid, src_fid)
    src_table = field2table.get(src_fid, "?")
    return link_name, src_name, src_table


# ===========================================================================
# 1. SQL SCHEMA
# ===========================================================================
sql = []
sql.append("-- Auto-generated by scripts/generate_supabase.py")
sql.append("-- Airtable -> Supabase landing schema. Stored fields only; computed fields excluded.")
sql.append("-- Primary key = Airtable record id (upsert target for one-way sync).\n")
sql.append("create schema if not exists airtable;\n")

for t in tables:
    tname = snake(t["name"])
    pf = t.get("primaryFieldId")
    stored = [f for f in t["fields"] if f["type"] not in COMPUTED]
    computed = [f for f in t["fields"] if f["type"] in COMPUTED]

    sql.append(f"-- ===== {t['name']}  ({len(stored)} stored, {len(computed)} computed/excluded) =====")
    sql.append(f"create table if not exists airtable.{ident(tname)} (")
    lines = ['    airtable_id   text primary key,']
    used = {"airtable_id"}
    for fld in stored:
        col = snake(fld["name"])
        base = col
        i = 2
        while col in used:
            col = f"{base}_{i}"; i += 1
        used.add(col)
        typ = pg_type(fld)
        comment = ""
        opts = fld.get("options") or {}
        if fld["type"] == "singleSelect":
            choices = [c["name"] for c in opts.get("choices", [])]
            comment = "  -- select: " + " | ".join(choices)
        elif fld["type"] == "multipleSelects":
            choices = [c["name"] for c in opts.get("choices", [])]
            comment = "  -- multi-select: " + " | ".join(choices)
        elif fld["type"] in ("multipleRecordLinks", "singleRecordLink"):
            tgt = id2table.get(opts.get("linkedTableId"), "?")
            single = " (single)" if opts.get("prefersSingleRecordLink") else ""
            comment = f"  -- link -> airtable.{snake(tgt)}{single}"
        elif fld["type"] in NUMERIC_TYPES and "precision" in opts:
            comment = f"  -- airtable precision {opts['precision']}"
        elif fld["type"] == "multipleAttachments":
            comment = "  -- attachment metadata (url, filename); files -> Supabase Storage later"
        if fld["id"] == pf:
            comment = ("  -- [PRIMARY FIELD]" + comment.replace("  --", " ·", 1)
                       if comment else "  -- [PRIMARY FIELD]")
        lines.append(f'    {ident(col):<28} {typ},{comment}')
    lines.append('    _synced_at    timestamptz not null default now()')
    sql.append("\n".join(lines))
    sql.append(");")
    if computed:
        names = ", ".join(f["name"] for f in computed)
        sql.append(f"-- EXCLUDED computed fields ({len(computed)}): {names}")
    sql.append("")

with open(os.path.join(ROOT, "sql", "01_schema.sql"), "w", encoding="utf-8") as f:
    f.write("\n".join(sql))

# ===========================================================================
# 2. FIELD MAPPING REVIEW
# ===========================================================================
md = []
md.append("# Field Mapping Review — Airtable → Supabase\n")
md.append("_Auto-generated. One row per **stored** field; computed fields are listed in "
          "`03-calculated-fields-todo.md`._\n")
md.append("**Conventions:** every table keyed by `airtable_id` (text). Links stored as "
          "`text[]` of Airtable record IDs. Selects stored as `text`/`text[]` (not enums). "
          "Numbers use unconstrained `numeric` to avoid sync rounding. Each table gets "
          "`_synced_at`.\n")
for t in tables:
    tname = snake(t["name"])
    stored = [f for f in t["fields"] if f["type"] not in COMPUTED]
    computed = [f for f in t["fields"] if f["type"] in COMPUTED]
    md.append(f"## `airtable.{tname}`  ({t['name']})")
    md.append(f"_{len(stored)} stored columns · {len(computed)} computed (deferred)_\n")
    md.append("| Airtable field | Airtable type | Postgres column | Postgres type |")
    md.append("|---|---|---|---|")
    for fld in stored:
        md.append(f"| {fld['name']} | {fld['type']} | {snake(fld['name'])} | {pg_type(fld)} |")
    md.append("")

with open(os.path.join(ROOT, "docs", "02-field-mapping-review.md"), "w", encoding="utf-8") as f:
    f.write("\n".join(md))

# ===========================================================================
# 3. CALCULATED FIELDS TODO  (md + csv)
# ===========================================================================
RECIPE = {
    "formula": "Postgres generated column or view expression",
    "rollup": "Aggregate (SUM/AVG/etc.) in a view over the linked child rows",
    "count": "COUNT(*) in a view over the linked child rows",
    "lookup": "JOIN to the linked table in a view",
    "multipleLookupValues": "JOIN to the linked table in a view (returns array)",
    "autoNumber": "bigserial / row_number() — usually drop",
    "createdTime": "created_at timestamptz default now()",
    "lastModifiedTime": "updated_at timestamptz via trigger",
    "createdBy": "set by app / auth.uid()",
    "lastModifiedBy": "set by app / auth.uid()",
    "button": "UI-only — drop",
}
rows = []
for t in tables:
    for fld in t["fields"]:
        if fld["type"] not in COMPUTED:
            continue
        opts = fld.get("options") or {}
        result_type = ((opts.get("result") or {}).get("type")) or ""
        if fld["type"] == "formula":
            logic = describe_formula(opts)
        elif fld["type"] in ("rollup", "lookup", "multipleLookupValues", "count"):
            link_name, src_name, src_table = describe_rollup_lookup(fld)
            if fld["type"] == "count":
                logic = f"count of linked records via [{link_name}]"
            else:
                logic = f"{src_table}.[{src_name}] via link [{link_name}]"
        else:
            logic = ""
        rows.append({
            "table": t["name"], "field": fld["name"], "airtable_type": fld["type"],
            "result_type": result_type, "logic": logic,
            "proposed_recreation": RECIPE.get(fld["type"], ""),
        })

with open(os.path.join(ROOT, "docs", "calculated-fields.csv"), "w", encoding="utf-8", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["table", "field", "airtable_type", "result_type",
                                      "logic", "proposed_recreation"])
    w.writeheader()
    w.writerows(rows)

md = []
md.append("# Calculated Fields — To Solve Later\n")
md.append(f"_{len(rows)} computed fields across {len(tables)} tables. These are **not** stored "
          "columns; recreate them as views / generated columns after base data is syncing._\n")
md.append("## Proposed recreation by type\n")
md.append("| Airtable type | Count | Proposed Postgres approach |")
md.append("|---|---|---|")
from collections import Counter
cc = Counter(r["airtable_type"] for r in rows)
for ty, n in cc.most_common():
    md.append(f"| {ty} | {n} | {RECIPE.get(ty,'')} |")
md.append("")
for t in tables:
    trows = [r for r in rows if r["table"] == t["name"]]
    if not trows:
        continue
    md.append(f"## {t['name']}  ({len(trows)})")
    md.append("| Field | Type | Result | Logic |")
    md.append("|---|---|---|---|")
    for r in trows:
        logic = r["logic"].replace("|", "\\|")
        md.append(f"| {r['field']} | {r['airtable_type']} | {r['result_type']} | {logic} |")
    md.append("")
with open(os.path.join(ROOT, "docs", "03-calculated-fields-todo.md"), "w", encoding="utf-8") as f:
    f.write("\n".join(md))

# ===========================================================================
# 4. ER DIAGRAM (Mermaid)
# ===========================================================================
m = ["# Entity Relationship Diagram\n",
     "Tables and their links (from Airtable `multipleRecordLinks`). "
     "Renders automatically on GitHub.\n", "```mermaid", "erDiagram"]
edges = set()
for t in tables:
    src = snake(t["name"])
    for fld in t["fields"]:
        if fld["type"] in ("multipleRecordLinks", "singleRecordLink"):
            tgt = snake(id2table.get((fld.get("options") or {}).get("linkedTableId"), "?"))
            if src == tgt:
                continue  # skip self-loops for readability
            key = tuple(sorted([src, tgt]))
            if key in edges:
                continue
            edges.add(key)
            m.append(f'    {src} }}o--o{{ {tgt} : links')
m.append("```")
with open(os.path.join(ROOT, "docs", "04-er-diagram.md"), "w", encoding="utf-8") as f:
    f.write("\n".join(m))

print("Generated:")
print("  sql/01_schema.sql")
print("  docs/02-field-mapping-review.md")
print("  docs/03-calculated-fields-todo.md")
print("  docs/calculated-fields.csv")
print("  docs/04-er-diagram.md")
print(f"\nStored fields: {sum(1 for t in tables for f in t['fields'] if f['type'] not in COMPUTED)}")
print(f"Computed fields: {len(rows)}")
print(f"Tables: {len(tables)}  |  Relationship edges (deduped, no self-loops): {len(edges)}")
